// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJpm26QZp6iofYnsu2z2cUri5fJr9gbvA',
    appId: '1:128014964279:web:d457f60d14de7d246151b2',
    messagingSenderId: '128014964279',
    projectId: 'cosmic-app-c3d90',
    authDomain: 'cosmic-app-c3d90.firebaseapp.com',
    storageBucket: 'cosmic-app-c3d90.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrepBvyGXJ_M0OPDV3M-U1nEc2tyGxAbk',
    appId: '1:128014964279:android:87146c7a40da5c9b6151b2',
    messagingSenderId: '128014964279',
    projectId: 'cosmic-app-c3d90',
    storageBucket: 'cosmic-app-c3d90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsrjdYxutqF17ymdvY4UgFrLBooj93pBQ',
    appId: '1:128014964279:ios:14c51d09cb38df546151b2',
    messagingSenderId: '128014964279',
    projectId: 'cosmic-app-c3d90',
    storageBucket: 'cosmic-app-c3d90.appspot.com',
    iosBundleId: 'com.example.cosmic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsrjdYxutqF17ymdvY4UgFrLBooj93pBQ',
    appId: '1:128014964279:ios:d4861eeab22320026151b2',
    messagingSenderId: '128014964279',
    projectId: 'cosmic-app-c3d90',
    storageBucket: 'cosmic-app-c3d90.appspot.com',
    iosBundleId: 'com.example.cosmic.RunnerTests',
  );
}
